/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiFactsRouteImport } from './routes/api/facts'
import { Route as ApiImageRouteImport } from './routes/api/image'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFactsRoute = ApiFactsRouteImport.update({
  id: '/api/facts',
  path: '/api/facts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageRoute = ApiImageRouteImport.update({
  id: '/api/image',
  path: '/api/image',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/facts': typeof ApiFactsRoute
  '/api/image': typeof ApiImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/facts': typeof ApiFactsRoute
  '/api/image': typeof ApiImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/facts': typeof ApiFactsRoute
  '/api/image': typeof ApiImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/chat' | '/api/facts' | '/api/image'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/chat' | '/api/facts' | '/api/image'
  id: '__root__' | '/' | '/api/chat' | '/api/facts' | '/api/image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiFactsRoute: typeof ApiFactsRoute
  ApiImageRoute: typeof ApiImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/facts': {
      id: '/api/facts'
      path: '/api/facts'
      fullPath: '/api/facts'
      preLoaderRoute: typeof ApiFactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image': {
      id: '/api/image'
      path: '/api/image'
      fullPath: '/api/image'
      preLoaderRoute: typeof ApiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiFactsRoute: ApiFactsRoute,
  ApiImageRoute: ApiImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
